default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  template: template0
  username: <%= ENV.fetch("DB_USERNAME", "ubuntu") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "sharemybag_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "sharemybag_test") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch("DB_NAME_PROD", "sharemybag_production") %>
  username: <%= ENV['DB_USERNAME_PROD'] %>
  password: <%= ENV['DB_PASSWORD_PROD'] %>
