development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "dev_fallback_" + SecureRandom.hex(64)) %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "test_fallback_" + SecureRandom.hex(64)) %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
